language: javascript
os: osx
osx_image: xcode9.3
rvm:
  - 2.2
  - jruby
  - 2.5.1
branches:
  only:
  - master
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
  - vendor/bundle
before_install:
  - nvm install && nvm use
install:
  - npm install
  - bundle install
script:
  - npm run ios:build
  - npm run android:build
