language: javascript

matrix:
  include:
    - os: linux
      language: android
    - os: osx
      osx_image: xcode9.3

branches:
  only:
  - master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
    - vendor/bundle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - nvm install && nvm use

install:
  - bundle install
  - npm install

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then npm run ios:build     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run android:build ; fi
